<?php
include ("./include.php");
?>

<p style="line-height:40px;">
<b>Implementation of pages on Instabook NY</b></br>

<b>Customer-Level Transactions: </b></br>
Register</br>
Sign in and sign out</br>
Post messages on personal pages</br>
Send a message</br>
Receive a message</br>
Delete a message</br>
 </br>
<b>Groups: </b></br>
Create a group</br>
Search for a user and add him to a group</br>
Join a group</br>
Unjoin a group</br>
Make a post</br>
Comment on a post</br>
Like a post</br>
Like a comment</br>
Remove a user from a group</br>
Remove a post</br>
Remove a comment</br>
Unlike a post</br>
Unlike a comment</br>
Modify a post</br>
Modify a comment</br>
Delete a group</br>
Rename a group</br>
Make a post on a group page</br>
Comment on a post on a group page</br>
Like a post on a group page</br>
Like a comment on a group page</br>
Remove one of their posts on a group page</br>
Remove a comment on a group page</br>
Unlike a post on a group page</br>
Unlike a comment on a group page</br>
Modify a post on a group page</br>
Modify a comment on a group page</br>
 </br>
<b>Manager-Level Transactions: </b></br>
Add, Edit and Delete information for an employee</br>
Obtain a sales report for a particular month</br>
Produce a comprehensive listing of all items being advertised on the site</br>
Produce a list of transactions by item name or by user name</br>
Produce a summary listing of revenue generated by a particular item, item type, or customer</br>
Determine which customer representative generated most total revenue</br>
Determine which customer generated most total revenue</br>
Produce a list of most active items</br>
Produce a list of all customers who have purchased a particular item</br>
Produce a list of all items for a given company</br>
 
</br>

<b>Customer-Representative-Level Transactions: </b></br>

Create an advertisement</br>
Delete an advertisement</br>
Record a transaction</br>
Add, Edit and Delete information for a customer</br>
Produce customer mailing lists</br>
Produce a list of item suggestions for a given customer (based on that customer's past transactions)</br>
Retrieve a customer's current groups</br>
For each of a customer's accounts, the account history</br>
Best-Seller list of items</br>
Personalized item suggestion list</br>
 </br>
</p>