<?php
include ("./include.php");

if(!$_SESSION[empl_id] || !$_SESSION[IsManager]){
  ?>
  <script>
  alert("Must be logged in as a manager!");
  history.back();
  </script>
  <?
}

if (isset($_POST[func])) {

  if (strcmp($_POST[func],'all_item_transactions') == 0) {

    $adv = $_POST[aId];

    $i_name = sql_query("SELECT ItemName From Advertisement WHERE Id=$adv");
    $i_name = mysqli_fetch_array($i_name);
    $i_name = $i_name[ItemName];


    echo "<h2> All Transactions for $i_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>User</th>".
          "<th>Item</th>".
          "<th>Description</th>".
          "<th>Units Purchased</th>".
          "<th>Date Purchased</th>".
        "</tr>";


        $query = "SELECT C.UserId, A.ItemName, A.Content, T.UnitsPurchased, T.DatePurchased ".
        	"FROM AdTransaction T, User C, Advertisement A ".
        	"WHERE T.Customer=C.AccountNumber AND T.Advertisement=A.Id AND A.Id = $adv";
        $result = sql_query($query);

        while ($row = mysqli_fetch_array($result)) {


          echo "<tr>" .
          "<td>$row[UserId]</td>" .
          "<td>$row[ItemName]</td>" .
          "<td>$row[Content]</td>" .
          "<td>$row[UnitsPurchased]</td>" .
          "<td>$row[DatePurchased]</td>" .
          "</tr>";
        }

        ?>
      </table>
        <?
  } else if (strcmp($_POST[func],'all_user_transactions') == 0) {

    $user = $_POST[uId];

    $i_name = sql_query("SELECT UserID From User WHERE AccountNumber=$user");
    $i_name = mysqli_fetch_array($i_name);
    $i_name = $i_name[UserID];


    echo "<h2> All Transactions for $i_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>User</th>".
          "<th>Item</th>".
          "<th>Units Purchased</th>".
          "<th>Date Purchased</th>".
        "</tr>";


        $query = "SELECT C.UserId, A.ItemName, T.UnitsPurchased, T.DatePurchased ".
        	"FROM AdTransaction T, User C, Advertisement A ".
        	"WHERE T.Customer=C.AccountNumber AND T.Advertisement=A.Id AND T.Customer = $user";
        $result = sql_query($query);

        while ($row = mysqli_fetch_array($result)) {


          echo "<tr>" .
          "<td>$row[UserId]</td>" .
          "<td>$row[ItemName]</td>" .
          "<td>$row[UnitsPurchased]</td>" .
          "<td>$row[DatePurchased]</td>" .
          "</tr>";
        }

        ?>
      </table>
        <?
  } else if (strcmp($_POST[func],'all_item_revenue') == 0) {

    $adv = $_POST[aId];

    $i_name = sql_query("SELECT ItemName From Advertisement WHERE Id=$adv");
    $i_name = mysqli_fetch_array($i_name);
    $i_name = $i_name[ItemName];


    echo "<h2> Total Revenue for $i_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>Item</th>".
          "<th>Total Revenue</th>".
        "</tr>";


        $query = "SELECT t.ItemName, SUM(t.Sale) As TotalRev FROM (SELECT (T.UnitsPurchased * A.UnitPrice) AS Sale, A.ItemName FROM AdTransaction T, Advertisement A WHERE T.Advertisement=$adv AND A.Id = $adv) t";
        $result = sql_query($query);

        while ($row = mysqli_fetch_array($result)) {


          echo "<tr>" .
          "<td>$i_name</td>" .
          "<td>$ $row[TotalRev]</td>" .
          "</tr>";
        }

        ?>
      </table>
        <?
  }else if (strcmp($_POST[func],'all_user_revenue') == 0) {

    $user = $_POST[uId];

    $i_name = sql_query("SELECT UserID From User WHERE AccountNumber=$user");
    $i_name = mysqli_fetch_array($i_name);
    $i_name = $i_name[UserID];


    echo "<h2> Total Revenue Generated by User $i_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>User</th>".
          "<th>Total Revenue Generated</th>".
        "</tr>";


        $query = "SELECT SUM(t.Sale) AS TotalRev FROM (SELECT  T.UnitsPurchased * A.UnitPrice AS Sale ".
	"FROM AdTransaction T, Advertisement A, User C ".
	"WHERE T.Advertisement=A.Id AND C.AccountNumber=T.Customer AND C.AccountNumber=$user) t";
        $result = sql_query($query);

        $row = mysqli_fetch_array($result);


          echo "<tr>" .
          "<td>$i_name</td>" .
          "<td>$ $row[TotalRev]</td>" .
          "</tr>";


        ?>
      </table>
        <?
  }else if (strcmp($_POST[func],'all_pref_revenue') == 0) {

    $prefID = $_POST[pId];

    $i_name = sql_query("SELECT Name From Preference WHERE Id=$prefID");
    $i_name = mysqli_fetch_array($i_name);
    $i_name = $i_name[Name];


    echo "<h2> Total Revenue for Item Preference $i_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>Item Category</th>".
          "<th>Total Revenue</th>".
        "</tr>";


        $query =  "SELECT SUM(t.Sale) AS TotalRev FROM (SELECT T.UnitsPurchased * A.UnitPrice AS Sale FROM AdTransaction T, Advertisement A WHERE T.Advertisement=A.Id AND A.PreferenceType=$prefID) t";
        $result = sql_query($query);

        while ($row = mysqli_fetch_array($result)) {


          echo "<tr>" .
          "<td>$i_name</td>" .
          "<td>$ $row[TotalRev]</td>" .
          "</tr>";
        }

        ?>
      </table>
        <?
  }else if (strcmp($_POST[func],'all_users_bought_item') == 0) {

    $adv = $_POST[aId];

    $i_name = sql_query("SELECT ItemName From Advertisement WHERE Id=$adv");
    $i_name = mysqli_fetch_array($i_name);
    $i_name = $i_name[ItemName];


    echo "<h2> All Users that have Purchased $i_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>UserId</th>".
          "<th>FirstName</th>".
          "<th>LastName</th>".
        "</tr>";


        $query = "SELECT DISTINCT C.UserId, C.FirstName, C.LastName FROM AdTransaction T, User C, Advertisement A WHERE T.Customer=C.AccountNumber AND T.Advertisement=A.Id AND A.Id = $adv";
        $result = sql_query($query);

        while ($row = mysqli_fetch_array($result)) {


          echo "<tr>" .
          "<td>$row[UserId]</td>" .
          "<td>$row[FirstName]</td>" .
          "<td>$row[LastName]</td>" .
          "</tr>";
        }

        ?>
      </table>
        <?
  }else if (strcmp($_POST[func],'company_items') == 0) {

    $c_id = $_POST[cId];

    $c_name = sql_query("SELECT Name From Company WHERE Id=$c_id");
    $c_name = mysqli_fetch_array($c_name);
    $c_name = $c_name[Name];


    echo "<h2> All Items Sold by Company $c_name </h2>".
      "<table class ='niceTable'>".
        "<tr>".
          "<th>Item Name</th>".
          "<th>Description</th>".
        "</tr>";


        $query = "SELECT A.ItemName, A.Content FROM Company C, Advertisement A WHERE A.Company=C.Id AND C.Id=$c_id";
        $result = sql_query($query);

        while ($row = mysqli_fetch_array($result)) {

          echo "<tr>" .
          "<td>$row[ItemName]</td>" .
          "<td>$row[Content]</td>" .
          "</tr>";
        }

        ?>
      </table>
        <?
  }



}


?>
